### ISSUE TITLE
Chapter 4 - Event Dispatchers - Actor Spawns in the wrong location

### ISSUE THREAD

**Issue by SethGibson** [PacktPublishing/-Blueprints-Visual-Scripting-for-Unreal-Engine-5#3]
In the exercise in Chapter 4 wherein the goal is to create a platform that spawns an effect on player collision, the new actor doesn't spawn at the location of the platform, it instead spawns in different locations, depending on the effect, although some effects WILL spawn in the correct location. 

If created in UE4, this exercise does execute correctly in both UE4 and UE5, but when I create the exercise in UE5 (5.3.2), the bug is present. Probably an editor issue, but something to be aware of.

**Comment by MarcosRomero** [comment]
Hi Seth,

Thank you for reporting the problem.

This is a bug that appears in some Blueprints of the Starter Content since
v5.2.

Access this link from my blog:
https://romeroblueprints.blogspot.com/2023/07/book-update-blueprints-for-unreal.html

Go to the topic named:
- Offset problem in Blueprints of Starter Content (v5.2)

There I show how to solve this issue.

Em ter., 13 de fev. de 2024 às 12:47, Seth Gibson ***@***.***>
escreveu:

**Comment by SethGibson** [comment]
Got it, Thank you So Much!
